/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master;

import Settings.MainSystemSetting;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author MS
 */
public class Login extends javax.swing.JFrame {
    
    public MainSystemSetting mnSetting = new MainSystemSetting();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        et_username = new javax.swing.JTextField();
        et_password = new javax.swing.JTextField();
        btLogin = new javax.swing.JButton();
        cb_admin = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 520));
        setSize(new java.awt.Dimension(410, 520));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Logistic");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 180, 400, 70);

        et_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(et_username);
        et_username.setBounds(70, 280, 260, 20);
        getContentPane().add(et_password);
        et_password.setBounds(70, 300, 260, 20);

        btLogin.setText("Login");
        btLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLoginMouseClicked(evt);
            }
        });
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btLogin);
        btLogin.setBounds(70, 350, 260, 23);

        cb_admin.setText("Admin");
        getContentPane().add(cb_admin);
        cb_admin.setBounds(70, 320, 81, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ami\\Downloads\\msi2 (1).png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 30, 240, 140);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void et_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_usernameActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLoginActionPerformed

    private void btLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLoginMouseClicked
            
        
        if(cb_admin.isSelected())
        {
            try {
                
                String checkdata = "SELECT count(*) from admin WHERE username = '"+et_username.getText().toString()+"' AND password = '"+et_password.getText().toString()+"'";
                mnSetting.ps = mnSetting.con.prepareStatement(checkdata);
                final ResultSet resultSet = mnSetting.ps.executeQuery();
                int count = 0;
                if(resultSet.next()) {
                   count = resultSet.getInt(1);
                }
                if(count > 0)
                {
                    Master plg = new Master();
                    plg.donotshowPanel();
                    plg.setVisible(true); 

                    this.dispose();
            
                }else
                {
                    JOptionPane.showMessageDialog(null, "Username Admin dan Password salah, silahkan coba lagi", "System", JOptionPane.DEFAULT_OPTION);
                
                }
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                System.out.println("Error Login\n"+ex);
            }
        }
        else
        {
            try {
                
                String checkdata = "SELECT count(*) from employee WHERE username = '"+et_username.getText().toString()+"' AND password = '"+et_password.getText().toString()+"'";
                mnSetting.ps = mnSetting.con.prepareStatement(checkdata);
                final ResultSet resultSet = mnSetting.ps.executeQuery();
                int count = 0;
                if(resultSet.next()) {
                   count = resultSet.getInt(1);
                }
                if(count > 0)
                {
                    ArrayList<DataEmployee> arraylist_data = new ArrayList<>();
                    
                    String select_data = "select *from employee WHERE username = '"+et_username.getText().toString()+"' AND password = '"+et_password.getText().toString()+"'"; 
                    ResultSet rs_data = mnSetting.stm.executeQuery(select_data);
                    DataEmployee dt = null;
//
                    while (rs_data.next()) {
                        dt = new DataEmployee(rs_data.getString("kode"), rs_data.getString("name"), rs_data.getString("gender"), rs_data.getString("username"), rs_data.getString("password"), rs_data.getString("kode_agent"));
                        arraylist_data.add(dt);
                    }
//                    

                    Transaction_Paket tp = new Transaction_Paket();
                    tp.kode_emp = dt.getKode();
                    tp.kode_agen_emp = dt.getId_dropoff_agent();
                    tp.donotShowany();
                    tp.setVisible(true); 
//                    JOptionPane.showMessageDialog(null, tp.kode_kota, "System", JOptionPane.DEFAULT_OPTION);

                    this.dispose();
            
                }else
                {
                    JOptionPane.showMessageDialog(null, "Username Employee dan Password salah, silahkan coba lagi", "System", JOptionPane.DEFAULT_OPTION);
                
                }
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                System.out.println("Error Login\n"+ex);
            }
        }
        
        
    }//GEN-LAST:event_btLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JCheckBox cb_admin;
    private javax.swing.JTextField et_password;
    private javax.swing.JTextField et_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
