/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import Settings.MainSystemSetting;

/**
 *
 * @author Ami
 */
public class Master extends javax.swing.JFrame {

    public MainSystemSetting mnSetting = new MainSystemSetting();
    private String jkel;

    /**
     * Creates new form Pelanggan
     */
    public Master() {
        initComponents();
        allVisible();
    }
    
    public void allVisible()
    {
        
        panel_pelanggan.setVisible(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_pelanggan = new javax.swing.JButton();
        btn_kota = new javax.swing.JButton();
        btn_costestimate = new javax.swing.JButton();
        btn_agen = new javax.swing.JButton();
        panel_pelanggan = new javax.swing.JPanel();
        et_kodepelanggan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        et_notelp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        et_alamat = new javax.swing.JTextArea();
        et_caripelanggan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        et_namapelanggan = new javax.swing.JTextField();
        btSimpanPelanggan = new javax.swing.JButton();
        btUbahPelanggan = new javax.swing.JButton();
        btHapusPelanggan = new javax.swing.JButton();
        btnClearpelanggan = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1090, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(1090, 480));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Master Data");

        btn_pelanggan.setText("Customer");
        btn_pelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseClicked(evt);
            }
        });

        btn_kota.setText("Kota");
        btn_kota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_kota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kotaMouseClicked(evt);
            }
        });

        btn_costestimate.setText("Cost Estimate");
        btn_costestimate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_costestimate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_costestimateMouseClicked(evt);
            }
        });

        btn_agen.setText("Drop Off Agen");
        btn_agen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_pelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_costestimate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_agen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_costestimate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_agen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 120, 430);

        panel_pelanggan.setBackground(new java.awt.Color(255, 255, 255));
        panel_pelanggan.setLayout(null);

        et_kodepelanggan.setToolTipText("Nama");
        et_kodepelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_kodepelangganActionPerformed(evt);
            }
        });
        panel_pelanggan.add(et_kodepelanggan);
        et_kodepelanggan.setBounds(10, 60, 300, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pelanggan");
        panel_pelanggan.add(jLabel11);
        jLabel11.setBounds(0, 0, 750, 30);

        jLabel12.setText("Kode Pelanggan");
        panel_pelanggan.add(jLabel12);
        jLabel12.setBounds(10, 40, 120, 20);

        jLabel13.setText("Jenis Kelamin");
        panel_pelanggan.add(jLabel13);
        jLabel13.setBounds(10, 150, 63, 14);

        rbLaki.setBackground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("Laki - laki");
        rbLaki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbLaki.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbLakiStateChanged(evt);
            }
        });
        rbLaki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbLakiMouseClicked(evt);
            }
        });
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });
        panel_pelanggan.add(rbLaki);
        rbLaki.setBounds(10, 170, 69, 23);

        rbPerempuan.setBackground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Perempuan");
        rbPerempuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbPerempuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPerempuanMouseClicked(evt);
            }
        });
        rbPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanActionPerformed(evt);
            }
        });
        panel_pelanggan.add(rbPerempuan);
        rbPerempuan.setBounds(110, 170, 79, 23);

        jLabel14.setText("No Handphone");
        panel_pelanggan.add(jLabel14);
        jLabel14.setBounds(10, 200, 100, 14);
        panel_pelanggan.add(et_notelp);
        et_notelp.setBounds(10, 220, 300, 20);

        jLabel15.setText("Alamat");
        panel_pelanggan.add(jLabel15);
        jLabel15.setBounds(10, 250, 90, 14);

        et_alamat.setColumns(20);
        et_alamat.setRows(5);
        jScrollPane2.setViewportView(et_alamat);

        panel_pelanggan.add(jScrollPane2);
        jScrollPane2.setBounds(10, 270, 300, 76);

        et_caripelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                et_caripelangganKeyTyped(evt);
            }
        });
        panel_pelanggan.add(et_caripelanggan);
        et_caripelanggan.setBounds(320, 60, 420, 20);

        jLabel16.setText("Cari Nama Pelanggan");
        panel_pelanggan.add(jLabel16);
        jLabel16.setBounds(320, 40, 190, 14);

        tablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Jenis Kelamin", "No Handphone", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePelanggan.getTableHeader().setReorderingAllowed(false);
        tablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelangganMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablePelanggan);

        panel_pelanggan.add(jScrollPane4);
        jScrollPane4.setBounds(320, 90, 420, 330);

        jLabel17.setText("Nama Pelanggan");
        panel_pelanggan.add(jLabel17);
        jLabel17.setBounds(10, 90, 120, 20);

        et_namapelanggan.setToolTipText("Nama");
        et_namapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_namapelangganActionPerformed(evt);
            }
        });
        panel_pelanggan.add(et_namapelanggan);
        et_namapelanggan.setBounds(10, 120, 300, 20);

        btSimpanPelanggan.setText("Simpan");
        btSimpanPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSimpanPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSimpanPelangganMouseClicked(evt);
            }
        });
        btSimpanPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanPelangganActionPerformed(evt);
            }
        });
        panel_pelanggan.add(btSimpanPelanggan);
        btSimpanPelanggan.setBounds(10, 400, 90, 23);

        btUbahPelanggan.setText("Ubah");
        btUbahPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btUbahPelanggan.setPreferredSize(new java.awt.Dimension(67, 23));
        btUbahPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btUbahPelangganMouseClicked(evt);
            }
        });
        panel_pelanggan.add(btUbahPelanggan);
        btUbahPelanggan.setBounds(120, 400, 90, 23);

        btHapusPelanggan.setText("Hapus");
        btHapusPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHapusPelanggan.setPreferredSize(new java.awt.Dimension(67, 23));
        btHapusPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHapusPelangganMouseClicked(evt);
            }
        });
        panel_pelanggan.add(btHapusPelanggan);
        btHapusPelanggan.setBounds(220, 400, 90, 23);

        btnClearpelanggan.setText("Clear");
        btnClearpelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearpelangganMouseClicked(evt);
            }
        });
        btnClearpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearpelangganActionPerformed(evt);
            }
        });
        panel_pelanggan.add(btnClearpelanggan);
        btnClearpelanggan.setBounds(10, 370, 300, 23);

        getContentPane().add(panel_pelanggan);
        panel_pelanggan.setBounds(140, 10, 750, 430);

        jLabel18.setText("Kelas  : S6L");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(900, 50, 150, 14);

        jLabel2.setText("Tugas Kelompok UAS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(900, 30, 130, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Adnan Jarkasih \nNPM : 201843501363\n\n2. Lina Murdiyanti \nNPM : 201843501561\n\n3. Andi Warman \nNPM : 201843500397\n\n4. Muhammad Luthfi Ramadhan \nNPM : 201843501403\n\n5. Andri Hidayatullah \nNPM : 201843501455\n\n6. Muhamad Saami \nNPM : 201843501620\n\n7. Cuhadiansah \nNPM : 201843501237\n\n8. Ridho Riono \nNPM : 201843500621");
        jScrollPane6.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(900, 70, 150, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseClicked
        // TODO add your handling code here:
        panel_pelanggan.setVisible(true);
        getConnection();
        getDataCustomer();
    }//GEN-LAST:event_btn_pelangganMouseClicked

    private void et_kodepelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_kodepelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_kodepelangganActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void rbPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPerempuanActionPerformed

    private void et_caripelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_caripelangganKeyTyped
        // TODO add your handling code here:
        System.out.println("typed");
        CariCustomer();
    }//GEN-LAST:event_et_caripelangganKeyTyped

    private void tablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelangganMouseClicked
        // TODO add your handling code here:
        String kode = (String) tablePelanggan.getValueAt(tablePelanggan.getSelectedRow(), 0);
        String nama = (String) tablePelanggan.getValueAt(tablePelanggan.getSelectedRow(), 1);
        String jeniskelamin = (String) tablePelanggan.getValueAt(tablePelanggan.getSelectedRow(), 2);
        String notelp = (String) tablePelanggan.getValueAt(tablePelanggan.getSelectedRow(), 3);
        String alamat = (String) tablePelanggan.getValueAt(tablePelanggan.getSelectedRow(), 4);
        
        et_kodepelanggan.setText(kode);
        et_namapelanggan.setText(nama);
        if(jeniskelamin.toLowerCase().equals("laki - laki"))
        {
            rbLaki.setSelected(true);
            rbPerempuan.setSelected(false);
        }else
        {
            rbLaki.setSelected(false);
            rbPerempuan.setSelected(true);
        }
        et_notelp.setText(notelp);
        et_alamat.setText(alamat);
    }//GEN-LAST:event_tablePelangganMouseClicked

    private void et_namapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_namapelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_namapelangganActionPerformed

    private void btSimpanPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSimpanPelangganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btSimpanPelangganMouseClicked

    private void btSimpanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanPelangganActionPerformed
        // TODO add your handling code here:
        if(rbLaki.isSelected())
        {
            jkel = rbLaki.getText().toString();
        }
        else
        {
            jkel = rbPerempuan.getText().toString();
        }
        
        if(et_kodepelanggan.getText().length() == 0 || et_namapelanggan.getText().length() == 0 || et_notelp.getText().length() == 0 || (rbLaki.isSelected() == false && rbPerempuan.isSelected() == false) || et_alamat.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data customer di atas", "System", JOptionPane.DEFAULT_OPTION);
        }else
        {
            getConnection();
            
            
            try {
                
                String checkPelanggan = "SELECT count(*) from customer WHERE kode = '"+et_kodepelanggan.getText().toString()+"'";
                mnSetting.ps = mnSetting.con.prepareStatement(checkPelanggan);
                final ResultSet resultSet = mnSetting.ps.executeQuery();
                int count = 0;
                if(resultSet.next()) {
                   count = resultSet.getInt(1);
                }
                if(count > 0)
                {
                    JOptionPane.showMessageDialog(null, "Kode "+et_kodepelanggan.getText().toString()+" sudah terdaftar, mohon gunakan kode yang lain", "System", JOptionPane.DEFAULT_OPTION);
                }else
                {
                    String createPelanggan = "insert into customer (kode,nama,jeniskelamin,notelp,alamat) values ('"+et_kodepelanggan.getText().toString()+"','"+et_namapelanggan.getText().toString()+"','"+jkel+"','"+et_notelp.getText().toString()+"','"+et_alamat.getText().toString()+"')";
                    mnSetting.stm.executeUpdate(createPelanggan);
                    getDataCustomer();
                    clearCustomerField();
                }
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                System.out.println("Error insert data pelanggan\n"+ex);
            }
            
        }
    }//GEN-LAST:event_btSimpanPelangganActionPerformed

    private void btUbahPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUbahPelangganMouseClicked
        // TODO add your handling code here:
        if(rbLaki.isSelected())
        {
            jkel = rbLaki.getText().toString();
        }
        else
        {
            jkel = rbPerempuan.getText().toString();
        }
        
        if(et_kodepelanggan.getText().length() == 0 || et_namapelanggan.getText().length() == 0 || et_notelp.getText().length() == 0 || (rbLaki.isSelected() == false && rbPerempuan.isSelected() == false) || et_alamat.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Mohon pilih daftar customer di kanan", "System", JOptionPane.DEFAULT_OPTION);
        }else
        {
            getConnection();
            
            
            try {
                
                String checkPelanggan = "SELECT count(*) from customer WHERE kode = '"+et_kodepelanggan.getText().toString()+"'";
                mnSetting.ps = mnSetting.con.prepareStatement(checkPelanggan);
                final ResultSet resultSet = mnSetting.ps.executeQuery();
                int count = 0;
                if(resultSet.next()) {
                   count = resultSet.getInt(1);
                }
                if(count > 0)
                {
                    String updatePelanggan = "update customer SET nama='"+et_namapelanggan.getText().toString()+"', jeniskelamin='"+jkel+"', notelp='"+et_notelp.getText().toString()+"', alamat='"+et_alamat.getText().toString()+"' where kode='"+et_kodepelanggan.getText().toString()+"'";
                    mnSetting.stm.executeUpdate(updatePelanggan);
                    JOptionPane.showMessageDialog(null, "Kode "+et_kodepelanggan.getText().toString()+" berhasil diperbarui", "System", JOptionPane.DEFAULT_OPTION);
                    getDataCustomer();
                    clearCustomerField();
                }else
                {
                    JOptionPane.showMessageDialog(null, "Kode "+et_kodepelanggan.getText().toString()+" tidak dikenal, Silahkan pilih salah satu daftar customer dikanan untuk mendapatkan kode customer", "System", JOptionPane.DEFAULT_OPTION);
                }
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                System.out.println("Error update data pelanggan\n"+ex);
            }
            
        }
    }//GEN-LAST:event_btUbahPelangganMouseClicked

    private void btHapusPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHapusPelangganMouseClicked
        // TODO add your handling code here:
        if(et_kodepelanggan.getText().length() == 0 || et_namapelanggan.getText().length() == 0 || et_notelp.getText().length() == 0 || (rbLaki.isSelected() == false && rbPerempuan.isSelected() == false) || et_alamat.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Mohon pilih daftar customer di kanan", "System", JOptionPane.DEFAULT_OPTION);
        }else
        {
            getConnection();            
            try {
                
                
                
                String checkCustomer = "SELECT count(*) from customer WHERE kode = '"+et_kodepelanggan.getText().toString()+"'";
                mnSetting.ps = mnSetting.con.prepareStatement(checkCustomer);
                final ResultSet resultSet = mnSetting.ps.executeQuery();
                int count = 0;
                if(resultSet.next()) {
                   count = resultSet.getInt(1);
                }
                if(count > 0)
                {
                    
                    int dialogResult = JOptionPane.showConfirmDialog (null, "Apakah kamu yakin ingin menghapus kode "+et_kodepelanggan.getText().toString()+"?","Warning",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                    if(dialogResult == JOptionPane.YES_OPTION){
                       String deletePelanggan = "delete from customer WHERE kode='"+et_kodepelanggan.getText().toString()+"'";
                        mnSetting.stm.executeUpdate(deletePelanggan);
                        JOptionPane.showMessageDialog(null, "Kode "+et_kodepelanggan.getText().toString()+" berhasil dihapus", "System", JOptionPane.DEFAULT_OPTION);
                        getDataCustomer(); 
                        clearCustomerField();
                    }
                    
                }else
                {
                    JOptionPane.showMessageDialog(null, "Kode "+et_kodepelanggan.getText().toString()+" tidak dikenal, Silahkan pilih salah satu daftar pelanggan dikanan untuk mendapatkan kode pelanggan", "System", JOptionPane.DEFAULT_OPTION);
                }
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                System.out.println("Error delete data customer\n"+ex);
            }
            
        }
    }//GEN-LAST:event_btHapusPelangganMouseClicked

    private void btnClearpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearpelangganMouseClicked
        // TODO add your handling code here:
        clearCustomerField();
    }//GEN-LAST:event_btnClearpelangganMouseClicked

    private void btnClearpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearpelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearpelangganActionPerformed

    private void rbLakiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbLakiMouseClicked
        // TODO add your handling code here:
        rbLaki.setSelected(true);
        if(rbLaki.isSelected())
        {
           rbPerempuan.setSelected(false);
        }else
        {
            
        }
        
        
    }//GEN-LAST:event_rbLakiMouseClicked

    private void rbPerempuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPerempuanMouseClicked
        // TODO add your handling code here:
        rbPerempuan.setSelected(true);
        if(rbPerempuan.isSelected())
        {
           rbLaki.setSelected(false);
        }else
        {
            
        }
    }//GEN-LAST:event_rbPerempuanMouseClicked

    private void rbLakiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbLakiStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiStateChanged

    private void btn_kotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kotaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_kotaMouseClicked

    private void btn_costestimateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_costestimateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_costestimateMouseClicked

    private void btn_agenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agenMouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master().setVisible(true);
            }
        });
    }
    
    public void getConnection()
    {
        
        if(mnSetting.con == null)
        {
            try {
                mnSetting.stm = mnSetting.con.createStatement();
                System.out.println("DB Connected");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Connection Failed\n"+ex, "System", JOptionPane.DEFAULT_OPTION);

            }
        }else
        {
            
            System.out.println("DB Still Connected");
        }
    }
    
    public void clearCustomerField()
    {
        et_kodepelanggan.setText("");
        et_namapelanggan.setText("");
        et_notelp.setText("");
        et_alamat.setText("");
    }
    
    public void getDataCustomer()
    {
        ArrayList<DataCustomer> arraylist_customer = new ArrayList<>();
            
        try {
            String select_customer = "select *from customer";
            ResultSet rs_customer = mnSetting.stm.executeQuery(select_customer);
            DataCustomer dtCustomer;
            while (rs_customer.next()) {
                dtCustomer = new DataCustomer(rs_customer.getString("kode"), rs_customer.getString("nama"), rs_customer.getString("jeniskelamin"), rs_customer.getString("notelp"), rs_customer.getString("alamat"));
                arraylist_customer.add(dtCustomer);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        DefaultTableModel model_Pelanggan = (DefaultTableModel)tablePelanggan.getModel();
        model_Pelanggan.setRowCount(0);
        Object[] row = new Object[5];
        for (int i = 0; i<arraylist_customer.size(); i++) {
            row[0] = arraylist_customer.get(i).getKode();
            row[1] = arraylist_customer.get(i).getNama();
            row[2] = arraylist_customer.get(i).getJeniskelamin();
            row[3] = arraylist_customer.get(i).getNotelp();
            row[4] = arraylist_customer.get(i).getAlamat();
            model_Pelanggan.addRow(row);
        }
        
    }
    
    public void CariCustomer()
    {
        
        ArrayList<DataCustomer> arraylist_customer = new ArrayList<>();
            
        try {
            String select_customer = "select * from customer where nama like '%" + et_caripelanggan.getText().toString() + "%'";
            ResultSet rs_customer = mnSetting.stm.executeQuery(select_customer);
            DataCustomer dtCustomer;
            while (rs_customer.next()) {
                dtCustomer = new DataCustomer(rs_customer.getString("kode"), rs_customer.getString("nama"), rs_customer.getString("jeniskelamin"), rs_customer.getString("notelp"), rs_customer.getString("alamat"));
                arraylist_customer.add(dtCustomer);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Cari Customer Failed\n"+ex, "System", JOptionPane.DEFAULT_OPTION);
        }
        
        DefaultTableModel model_Pelanggan = (DefaultTableModel)tablePelanggan.getModel();
        model_Pelanggan.setRowCount(0);
        Object[] row = new Object[5];
        for (int i = 0; i<arraylist_customer.size(); i++) {
            row[0] = arraylist_customer.get(i).getKode();
            row[1] = arraylist_customer.get(i).getNama();
            row[2] = arraylist_customer.get(i).getJeniskelamin();
            row[3] = arraylist_customer.get(i).getNotelp();
            row[4] = arraylist_customer.get(i).getAlamat();
            model_Pelanggan.addRow(row);
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHapusPelanggan;
    private javax.swing.JButton btSimpanPelanggan;
    private javax.swing.JButton btUbahPelanggan;
    private javax.swing.JButton btnClearpelanggan;
    private javax.swing.JButton btn_agen;
    private javax.swing.JButton btn_costestimate;
    private javax.swing.JButton btn_kota;
    private javax.swing.JButton btn_pelanggan;
    private javax.swing.JTextArea et_alamat;
    private javax.swing.JTextField et_caripelanggan;
    private javax.swing.JTextField et_kodepelanggan;
    private javax.swing.JTextField et_namapelanggan;
    private javax.swing.JTextField et_notelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panel_pelanggan;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTable tablePelanggan;
    // End of variables declaration//GEN-END:variables
}
